### ISSUE TITLE
Issue at Setup

### ISSUE THREAD

**Issue by SilviuMihai** [azure-ad-b2c/Scripts#13]
Hello, 

I am using the following sample of code from Microsoft Identity Platform [2-call-api-b2c](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/3-Authorization-II/2-call-api-b2c), but with the custom policy starter pack from [custom policy](https://learn.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-custom-policy).
For the custom policy starter pack I used Local Accounts.
This was recommended from [B2CIEF Setup](https://b2ciefsetupapp.azurewebsites.net/).
Also when I am trying to use [change-sign-in-name](https://b2ciefsetupapp.azurewebsites.net/Home/Experimental?sampleFolderName=change-sign-in-name), same issue I am encountering. 

So for what I encountered I add the b2c domain name, and than redirects me to sign in with my email address and than I will encounter the issue bellow. 
I am receiving the following error by using the Begin Setup that was recommended and I cannot understand where it is the issue:
_This b2ciefsetupapp.azurewebsites.net page can’t be found
No webpage was found for the web address: https://b2ciefsetupapp.azurewebsites.net/Error?msg=QUFEU1RTNTAwMjAyOiBVc2VyIGFjY291bnQgJ3tFbWFpbEhpZGRlbn0nIGZyb20gZXh0ZXJuYWwgaWRlbnRpdHkgcHJvdmlkZXIgJ2xpdmUuY29tJyBpcyBub3Qgc3VwcG9ydGVkIGZvciBBUEkgdmVyc2lvbiAnMi4wJy4gTWljcm9zb2Z0IGFjY291bnQgcGFzcy10aHJ1IHVzZXJzIGFuZCBndWVzdHMgYXJlIG5vdCBzdXBwb3J0ZWQgYnkgdGhlIHRlbmFudC1pbmRlcGVuZGVudCBlbmRwb2ludC4NClRyYWNlIElEOiAyYjc3MmUyNC1hYzViLTQwMGMtOTEwZi03OTczZGZhMjI0MDINCkNvcnJlbGF0aW9uIElEOiAxODg4YzVhYi01MWJkLTRkOGYtYmJmNy1jYzg2MjNhMzczMGUNClRpbWVzdGFtcDogMjAyMi0xMS0yOSAwODo0NDo0NFo
HTTP ERROR 404_

**What to check ? Where I could possibly set something wrong ?**
Information Question: Could I use User Flow with a custom policy like [change-sign-in-name](https://b2ciefsetupapp.azurewebsites.net/Home/Experimental?sampleFolderName=change-sign-in-name)
And is a must to add the custom starter pack ?

**Comment by miquel-dev** [comment]
I am experimenting the same issue when trying to setup auto-account-linking sample.

**Comment by SilviuMihai** [comment]
Hello @miquel-dev, also for me the Usage part of the [B2CIEF Setup part](https://b2ciefsetupapp.azurewebsites.net/) is a little bit confusing. After posting the same issue on different locations I got an answer, you can see the answer here -> [check link the see answer](https://github.com/azure-ad-b2c/samples/issues/487) (Thank you again @JasSuri)
You can follow the steps from there to confirm for yourself, but I will also added it here.
Steps:
1. Go to the Azure portal, and select your B2C directory
2. Create a new user, **user@tenantname.onmicrosoft.com** (Check Manage -> Users section, there you will see how you can create one)
3. Make the new user a Global Admin (To create a Global Admin, you can do it through the user itself by selecting Assigned Roles or through Roles and administrators)
4. Try the setup tool again, when asked to login, use your newly created account **user@tenantname.onmicrosoft.com** (this username it can be taken when you _assigned the Global Admin to the user_)
5. You can read the usage parte again of the setup page and also aso you will be encountering another steps.
I hope it helps. Good luck
